### ISSUE TITLE
Turn off dependabot

### ISSUE THREAD

**Issue by tarunbatra** [anshulsahni/easy-raseed#29]
I think we should turn off dependabot alerts, at least till we go live, because then we can just run `npm outdated`. A vulnerability in unreleased product is no vulnerability.

**Comment by anshulsahni** [comment]
> A vulnerability in unreleased product is no vulnerability.

Fair point, will close this, for now, got ambitious more than required

**Comment by anshulsahni** [comment]
This is done :heavy_check_mark:
